name: Quality

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts

      - name: PHPStan
        uses: php-actions/phpstan@v3

      - name: Run PHP-CS-Fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff --dry-run -v

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          flags: unittests